<svelte:head><title>Conditions d'utilisations</title></svelte:head>
<article class="max-w-3xl mx-auto">
    <h1>Conditions d'utilisation</h1>
    <h2>Article 1: Généralités</h2>
    <p>Les conditions et dispositions ci-dessous règlent l’utilisation du Site Web du L’Incubateur du Campus Numérique, portant le nom de domaine LIEN DU SITE de même que de tous les autres Sites Web qui ont été ou seraient développés par le Campus Numérique, ci-après dénommés conjointement le Site Web.</p>
    <p>Ce Site Web a été créé par les élèves de dernière année E-business (Condorcet) et est géré par l’Incubateur du Campus Numérique, dont le siège social est établi à l’adresse Rue du Progrès 24, 7503 Tournai. Pour plus d’informations, vous pouvez envoyer un e-mail aux partenaires concernés par votre demande.</p>
    <p>En accédant au Site Web et en l’utilisant, vous acceptez les présentes conditions d’utilisation sans aucune réserve et vous engagez à les respecter.</p>
    <p>L’utilisation de ce Site Web n’entraînera pas la création d’un quelconque accord de coopération. Si l’une des dispositions des présentes conditions d’utilisation est inapplicable ou contraire à une disposition légale impérative, cette inapplicabilité n’aura aucun effet sur la validité ou l’applicabilité des autres dispositions.</p>
    <p>L’Incubateur du Campus Numérique se réserve le droit de modifier les dispositions des présentes conditions d’utilisation et l’utilisateur est dès lors prié de les consulter préalablement à toute nouvelle utilisation. Les présentes conditions sont des conditions spécifiques qui ont uniquement trait à l’utilisation du Site Web de l’Incubateur du Campus Numérique, ainsi qu’à toutes les autres initiatives internet et/ou de réseau de l’Incubateur du Campus Numérique (voir ci-dessus), et doivent être complétées des conditions générales de l’Incubateur du Campus Numérique qui restent intégralement d’application à la relation juridique entre l’Incubateur du Campus Numérique et le client/utilisateur.</p>
    <h2>Article 2: Accès au Site Web</h2>
    <p>L’Incubateur du Campus Numérique met tout en œuvre pour, dans la mesure du possible, assurer l’accès à son Site Web 7 jours sur 7 et 24 heures sur 24, sans aucune garantie quelle qu’elle soit en la matière.</p>
    <p>Cet accès peut toutefois être interrompu, notamment en cas de maintenance et de mise à jour, en cas de panne ou pour d’autres raisons techniques.</p>
    <h2>Article 3: Droits de propriété intellectuelle</h2>
    <p>Le Site Web, y compris les textes, la structure, la mise en pages, les composantes graphiques, la présentation, les logos, le logiciel et l’ensemble d’autres éventuels éléments contenus dans ce Site Web, sont protégés par les droits de propriété intellectuelle de l’Incubateur du Campus Numérique, ses éventuels fournisseurs ou partenaires. Ces droits de propriété intellectuelle concernent entre autres, sans que cette énumération soit limitative : le droit d’auteur, les droits voisins, les droits afférents aux banques de données et les droits des marques.</p>
    <p>D’autres noms de produits ou d’entreprises mentionnés sur ce Site Web peuvent être des marques de leurs propriétaires respectifs. Sans l’autorisation écrite et préalable de l’ayant droit ou de l’Incubateur du Campus Numérique, il est interdit à l’utilisateur de modifier, copier, distribuer, communiquer, traduire, diffuser, reproduire, publier, accorder avec licence, céder ou vendre les informations, logiciels, produits ou services obtenus sur ces sites. Il lui est également interdit de créer des travaux dérivés des éléments susmentionnés.</p>
    <p>La même disposition s’applique aux extraits de travaux proposés sur ce Site Web, même si ceux-ci sont offerts gratuitement. Toute infraction à ces droits de propriété intellectuelle peut donner lieu à des poursuites au civil et au pénal.</p>
    <p>Toute reproduction, en tout ou en partie, du contenu de l’Incubateur du Campus Numérique est strictement interdite.</p>
    <h2>Article 4: Responsabliité</h2>
    <p>Ce Site Web est destiné à fournir des informations générales concernant les activités de l’Incubateur du Campus Numérique et de ses partenaires.</p>
    <p>L’Incubateur du Campus Numérique et ses fournisseurs d’informations déclinent toute responsabilité en cas de pannes, d’interruptions ou d’erreurs de son Site Web de même que pour les conséquences qui pourraient en découler pour l’utilisateur ou des tiers.</p>
    <p>Les informations présentées sur ce Site Web peuvent contenir des inexactitudes techniques ou sur le plan du contenu ou des fautes de frappe. L’Incubateur du Campus Numérique n’accorde dès lors aucune garantie quelle qu’elle soit concernant l’exactitude ou l’actualisation des informations proposées sur ce Site Web.</p>
    <p>L’Incubateur du Campus Numérique ne sera en aucun cas tenue responsable des actes illégitimes, des dommages indirects résultant des présentes conditions, de sa responsabilité contractuelle ou de sa responsabilité du fait des produits ou de quelques dommages directs, indirects ou accidentels que ce soient, tels que des pertes d’exploitation, des pertes de bénéfices, des pertes d’opportunités, des pertes (d’exploitation), des stagnations de l’exploitation ou des coûts (de personnel), même si ceux-ci devaient résulter d’une faute grave ou d’une faute répétitive causée par le Site Web (y compris le fonctionnement technique ou l’indisponibilité), de virus informatiques, de délits informatiques, d’actes de piratage informatique et ce, même si l’Incubateur du Campus Numérique avait été  avertie de ces dangers.</p>
    <p>L’Incubateur du Campus Numérique ne sera pas davantage responsable en cas de dommages ou de perturbations temporaires ou permanents provoqués aux données ou au matériel informatique de l’utilisateur durant l’accès au Site Web, durant la consultation des pages du Site Web ou, généralement, durant le transfert de fichiers et de programmes informatiques qui constituent le Site Web vers son matériel de réception. L’Incubateur du Campus Numérique décline plus particulièrement toute responsabilité en cas de transfert éventuel de virus informatiques par le biais de son Site Web.</p>
    <p>L’Incubateur du Campus Numérique ne sera nullement tenue responsable de l’utilisation frauduleuse de ses moyens de diffusion.</p>
    <p>L’Incubateur du Campus Numérique décline toute responsabilité en cas d’effraction de ses systèmes informatiques et concernant le pillage de données qui pourrait en découler. L’Incubateur du Campus Numérique met néanmoins tous les moyens en œuvre en vue d’éviter toute effraction non autorisée.</p>
    <h2>Article 5: Traitement des données à caractère personnel (PROTECTION DE LA VIE PRIVEE)</h2>
    <h2>Article 6: Hyperliens</h2>
    <p>Les espaces Web en dehors des domaines et sous-domaines LIEN DU SITE et, plus particulièrement, les espaces vers lesquels l’utilisateur peut être renvoyé par le biais de liens hypertextes sur les pages de ce Site Web restent l’entière responsabilité des titulaires de ces espaces Web.</p>
    <p>L’Incubateur du Campus Numérique ne peut, en effet, exercer aucun contrôle permanent de ces espaces Web, ni accepter une quelconque responsabilité pour leur contenu. L’insertion de ces liens n’implique aucune approbation par le L’Incubateur du Campus Numérique des éléments contenus dans ce Site Web.</p>
    <p>L’Incubateur du Campus Numérique décline par conséquent toute responsabilité concernant les données de quelque nature que ce soit, contenues dans ou diffusées sur ces espaces Web auxquels il est fait référence et concernant le traitement de données à caractère personnel qui y est exécuté.</p>
    <h2>Article 7: Droit applicable et compétence</h2>
    <p>Tous les litiges associés au Site Web (à son utilisation) ou qui en découlent seront exclusivement soumis au droit belge. A cet effet, le tribunal de première instance de Tournai, le tribunal de commerce de Tournai et la justice de paix du premier canton de Tournai sont exclusivement compétents. Seuls ces tribunaux seront saisis pour des citations lancées contre l’Incubateur du Campus Numérique.</p>
    <p>L’Incubateur du Campus Numérique se réserve toutefois le droit de refuser l’accès à son Site Web à tout utilisateur, à tout moment, unilatéralement et sans notification préalable, que ce soit en tout ou en partie, plus particulièrement en cas de violation évidente des présentes conditions par l’utilisateur. L’utilisation de ce Site Web n’est pas autorisée dans les pays où les présentes dispositions, y compris le présent paragraphe, ne s’appliquent pas.</p>
    <p>Si vous n’êtes pas d’accord avec le contenu des présentes conditions générales, le seul recours possible consiste à ne plus utiliser le Site Web.</p>
</article>
