<svelte:head><title>Protection des données</title></svelte:head>

<article class="max-w-3xl mx-auto">
    <h1>Protection des données</h1>
    <h2>Informations générales</h2>
    <p>Le texte ci-après détaille la façon dont l’incubateur du campus numérique utilise et collecte vos données personnelles et vous informe des mesures prises pour assurer leur protection dans le cadre de l’utilisation du Site web conformément aux dispositions du Règlement du Parlement européen et du Conseil relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données, et abrogeant la directive 95/46/CE (Référence 2016/679 – règlement général sur la protection des données).</p>
    <p>l’incubateur du campus numérique protège la vie privée de ses internautes en respectant la règlementation applicable en vigueur.</p>
    <p>l’incubateur du campus numérique est susceptible de collecter vos données personnelles, notamment par : lors d’un abonnement à la Newsletter électronique proposée par l’incubateur du campus numérique, lors de votre utilisation de notre service de mise en relation téléphonique directe avec le Service commercial et Marketing de l’incubateur du campus numérique.</p>
    <p>Les « données personnelles » font référence aux informations vous concernant en tant que personne physique que vous communiquez volontairement en remplissant un formulaire figurant sur le site web de l’incubateur du campus numérique, ou que l’incubateur du campus numérique collecte dans le cadre de votre navigation et qui, quelle qu’en soit la nature, permettent de vous identifier, directement ou non. Les données personnelles regroupent des données nominatives (telles que vos noms, coordonnées) et des données d’identification électronique disponibles sur ou à partir de votre ordinateur (telles que les « cookies », les « adresses IP » ou les préférences de votre navigateur). Vos données d’identification électronique permettent d’identifier votre terminal de connexion ou les pages consultées sur le site web de l’incubateur du campus numérique au cours de votre navigation et sont généralement insuffisantes à elles seules pour vous identifier de manière nominative.</p>
    <p>Identité du responsable de traitement et Finalités poursuivies par le traitement Les données personnelles collectées sur le présent site web de l’incubateur du campus numérique peuvent être utilisées par l’incubateur du campus numérique (ci-après désigné l’incubateur du campus numérique), société ASBL, possédant le numéro d’entreprise suivant BE 0647 725 022 ayant son siège social Quai Saint-Brice 35 à 7500 Tournai, en tant que responsable du traitement à des fins de :- gérer la relation avec ses clients et prospects via l’abonnement à la Newsletter. L’envoi d’invitations à des événements en rapport avec l’entrepreneuriat.</p>
    <p>Certaines des données personnelles collectées nous permettront de vous adresser des newsletters informatives et des sollicitations commerciales par e-mail. Nous veillerons à recueillir votre consentement préalable sur le formulaire de collecte présent sur le site web de l’incubateur du campus numérique en cochant la case “J’accepte de recevoir des emails d’informations”.</p>
    <p>Les informations indispensables à l’incubateur du campus numérique pour remplir les missions décrites ci-dessus sont signalées par un astérisque dans les différentes pages du site web de l’incubateur du campus numérique. Les autres informations ont un caractère facultatif et nous permettent de mieux vous connaître et d’améliorer nos communications et services à votre égard. Les informations collectées par l’incubateur du campus numérique sont notamment vos nom, prénom, adresse e-mail.</p>
    <p>Droits que le visiteur détient pour contrôler ses données (droit d’accès, de rectification, d’opposition) Les utilisateurs ayant fournis leurs données personnelles par le biais du site web de l’incubateur du campus numérique disposent d’un droit d’accès et de rectification des données personnelles les concernant qui sont inexactes par e-mail : en envoyant un courriel à info@entreprendrewapi.be</p>
    <p>Les utilisateurs disposent également d’un droit d’opposition au traitement de leurs données pour des motifs légitimes ainsi qu’un droit d’opposition à ce que ces données continuent d’être utilisées à des fins de prospection commerciale, en contactant le service indiqué ci-dessus. Le site web de l’incubateur du campus numérique propose aux internautes de s’abonner à une lettre d’information appelée « Newsletter » qui contient notamment des informations sur les actualités de l’incubateur du campus numérique, ou encore sur les événements, etc…</p>
    <p>l’incubateur du campus numérique propose aux internautes qui ne souhaitent plus recevoir de Newsletter de se désabonner : - soit par un simple clic sur le lien de désinscription situé en bas de chaque Newsletter.</p>
    <p>Afin que nous puissions satisfaire cette demande, vous devrez nous faire parvenir les éléments nécessaires à votre identification : nom, prénom, e-mail.</p>
    <h2>Partage et divulgation des données personnelles</h2>
    <p>L’incubateur du campus numérique et les prestataires de l’incubateur du campus numérique sont les seules destinataires des données collectées. Au sein de la société l’incubateur du campus numérique, vos données personnelles peuvent être communiquées aux départements en charge de la gestion des relations clients de l’incubateur du campus numérique. Les prestataires extérieurs auxquels vos données personnelles sont susceptibles d’être communiquées sont notamment nos prestataires en charge de l’hébergement.</p>
    <p>l’incubateur du campus numérique ne transmet vos données personnelles à un tiers que lorsque : - vous nous avez donné votre accord préalable pour le partage de ces informations; - l’incubateur du campus numérique doit partager ces informations avec ses prestataires et notamment ses prestataires techniques pour vous fournir le service que vous avez demandé (par exemple l’envoi d’une Newsletter); - l’incubateur du campus numérique reçoit la requête d’une autorité judiciaire ou de toute autorité administrative habilitée par la loi sollicitant la communication de ces informations conformément aux dispositions législatives en vigueur.</p>
    <h2>Conservation des données</h2>
    <p>L’incubateur du campus numérique pourra être amené à conserver vos données personnelles pendant une période illimitée.</p>
    <h2>Mesures de sécurité</h2>
    <p>L’incubateur du campus numérique fait de son mieux pour protéger vos données personnelles contre les dommages, pertes, détournements, intrusions, divulgations, altérations ou destructions.</p>
    <p>Les systèmes informatiques de l’incubateur du campus numérique font l’objet d’une protection physique et logicielle conforme à l’état de l’art. Des procédures de sauvegarde physique et électronique des données collectées sur le site sont mises en œuvre, conformément à la législation européenne en vigueur relatives à la protection des données personnelles.</p>
    <p>Les salariés de l’incubateur du campus numérique qui, du fait de leur fonction, auraient accès à vos données personnelles s’engagent à la plus grande confidentialité à cet égard.</p>
    <p>Toutefois, l’incubateur du campus numérique ne maîtrise pas les risques liés au fonctionnement d’Internet et attire votre attention sur l’existence d’éventuels risques en terme de pertes ponctuelles de données ou d’atteinte à la confidentialité des données transitant via ce réseau. Les informations proposées sur le Site pourront être interrompues pour des cas de force majeure ou indépendants de la volonté de l’incubateur du campus numérique ou de faits ne relevant pas de la responsabilité de l’incubateur du campus numérique.</p>
    <p>Informations relatives aux cookies et aux préférences du navigateur Tout d’abord, précisons qu’un cookie (également appelé « témoin de connexion » ou « balise web ») est un fichier inscrit sur votre disque dur par un serveur Internet pour une durée temporaire définie, afin de faciliter votre navigation et d’améliorer la qualité du site web de l’incubateur du campus numérique. Il convient de distinguer entre les cookies dits « cookies de navigation » et les « cookies d’analyse statistique ».</p>
    <p>Les cookies de navigation permettent à l’incubateur du campus numérique de mémoriser des informations telles que votre adresse e-mail, vos identifiants de « Compte », les termes de recherche que vous avez effectuées dans le moteur de recherche et ce, afin de faciliter votre navigation à l’intérieur du Site ; leur durée est limitée à la durée de votre session Internet, c’est-à-dire 20 minutes à compter de votre dernière action sur l’une des pages du site.</p>
    <p>l’incubateur du campus numérique s’appuie également sur certaines préférences de votre navigateur telles que la langue ou l’activation du JavaScript afin de faciliter votre navigation. Par exemple, la détection de la langue de votre navigateur permet à l’incubateur du campus numérique de vous proposer la version du Site la plus appropriée.</p>
    <p>Les cookies d’analyse statistique permettent à l’incubateur du campus numérique de stocker des informations relatives à votre navigation sur le Site telles que les pages que vous avez consultées, la date et l’heure de la consultation, le lieu de votre connexion etc. Ces cookies ne nous permettent pas de vous identifier personnellement, les données qu’ils recueillent sont ensuite agrégées et attribuées à un visiteur unique impersonnel. Ces données permettent à l’incubateur du campus numérique d’analyser la pertinence des contenus du Site et de tenter de les améliorer. Leur durée peut aller jusqu’à 2 ans, afin de permettre des analyses comparatives dans le temps. Pour ce faire, l’incubateur du campus numérique utilise l’outil Google Analytics.</p>
    <p>Vous pouvez refuser les cookies en modifiant les paramètres de votre navigateur Internet. Cette opération entraînera cependant la suppression de tous les cookies utilisés par le navigateur, y compris ceux employés par d’autres sites web, ce qui peut conduire à l’altération ou la perte de certains réglages ou informations. La suppression des cookies peut être de nature à modifier, voire à rendre difficile la navigation sur le Site de l’incubateur du campus numérique.</p>
    <p>Nous vous informons que vous pouvez vous opposer à l’enregistrement de cookies en configurant votre navigateur de la manière suivante :</p>
    <p>Pour Google Chrome 5 et plus:</p>
    <p>1. Cliquez sur Paramètres 2. Cliquez sur Avancés 3. Dans la setion « Confidentialité et sécurité », cliquez sur Paramètres du contenu 4. Cliquez sur Cookies5. Désactiver les cookies</p>
    <p>Pour Microsoft Internet Explorer 11.0 et plus :</p>
    <p>1. choisissez le menu “Outils” (ou “Tools”), puis “Options Internet” (ou “Internet Options”). 2. cliquez sur l’onglet “Confidentialité” (ou “Confidentiality”) 3. sélectionnez le niveau souhaité à l’aide du curseur.</p>
    <p>Pour Firefox :</p>
    <p>1. choisissez le menu “Outils”>”Options” 2. cliquez sur l’option “Vie privée”</p>
    <p>Pour Safari 3.x pour Mac OS X</p>
    <p>1. choisissez le menu “Editions” 2. cliquez sur l’option “Préférences” 3. cliquez sur l’option “Sécurité” 4. cliquer sur « Afficher les cookies ».</p>
</article>